### ISSUE TITLE
Read LNK file structure from file or buffer

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.shellitem#17]
I would like to use this the `Lnk` object to read the structure from a buffer instead of a file, to create a jump list parser in `dissect.target`.

https://github.com/fox-it/dissect.shellitem/blob/main/dissect/shellitem/lnk/lnk.py#L369-L380

**Comment by Horofic** [comment]
Will close this issue when the proposed changes in #18 are reflected
